version: '3'

networks:
  web:
    external: true

volumes:
  storage:

services:
  ausleihe:
    image: ghcr.io/chaostreff-flensburg/simple-borrow:latest
    restart: always
    volumes:
      - storage:/var/www/html/storage
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ausleihe.rule=Host(`ausleihe.chaostreff-flensburg.de`)"
      - "traefik.http.routers.ausleihe.entrypoints=https,http"
      - "traefik.http.services.ausleihe.loadbalancer.server.port=9000"
      - "traefik.http.routers.ausleihe.tls.certresolver=mytlschallenge"
      - "traefik.docker.network=web"
    networks:
      - web
    env_file:
      - .env
    logging:
      options:
        max-size: "10m"
    entrypoint: ["bash", "/var/www/html/docker/entrypoint.sh"]
    command: ["bash", "/var/www/html/docker/startup.sh"]

  schedule:
    image: ghcr.io/chaostreff-flensburg/simple-borrow:latest
    restart: always
    volumes:
      - storage:/var/www/html/storage
    depends_on:
      - ausleihe
    env_file:
      - .env
    logging:
      options:
        max-size: "10m"
    command: ["bash", "/var/www/html/docker/schedule.sh"]

  queue:
    image: ghcr.io/chaostreff-flensburg/simple-borrow:latest
    restart: always
    depends_on:
      - ausleihe
    volumes:
      - storage:/var/www/html/storage
    env_file:
      - .env
    logging:
      options:
        max-size: "10m"
    command: ["bash", "/var/www/html/docker/queue.sh"]
